contract:
  name: producer_lending_loans
  version: 2.0.0
dataset:
  name: lending_loans
fields:
  - name: loan_id
    type: integer
    required: true
    rules:
      not_null: true
      unique: true
  - name: customer_id
    type: integer
    required: true
    rules:
      not_null: true
  - name: product_type
    type: string
    required: true
    rules:
      enum: [term, revolver]
  - name: status
    type: string
    required: true
    rules:
      enum: [active, delinquent, closed]
  - name: currency
    type: string
    required: true
    rules:
      regex: '^[A-Z]{3}$'
  - name: principal_balance
    type: float
    required: true
    rules:
      min: 0
      max: 20000000.0
      not_null: true
  - name: interest_rate
    type: float
    required: true
    rules:
      min: 0
      max: 0.25
  - name: opened_at
    type: string
    required: true
    rules:
      regex: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$'
