# ============================================================================
# PRODUCER CONTRACT: Lending Loans
# ============================================================================
# Scenario: Commercial & Institutional Banking Data Product (NatWest-style)
# Owner: Data Product Team (Producer)
# Strictness: STRICT - Authoritative loan portfolio data
#
# Business Purpose:
#   - Master registry of all commercial and institutional loans
#   - Enforces strict loan type classification, balance limits, and interest rate bounds
#   - All fields required with no nulls for credit risk integrity
#   - Used by Lending Operations, Finance Analytics, and Risk/Exposure teams
#
# Key Rules:
#   - loan_id: unique loan identifier
#   - customer_id: foreign key to customers table (must exist)
#   - product_type: term or revolver only (loan classification)
#   - status: active, delinquent, or closed
#   - currency: ISO 4217 3-letter code (e.g., GBP, USD, EUR)
#   - principal_balance: 0 to 20M range (large commercial loans)
#   - interest_rate: 0% to 25% (0.0 to 0.25 float)
#   - opened_at: datetime in YYYY-MM-DD HH:MM:SS format
# ============================================================================

contract:
  name: producer_lending_loans
  version: 2.0.0
dataset:
  name: lending_loans
fields:
  - name: loan_id
    type: integer
    required: true
    rules:
      not_null: true
      unique: true
  - name: customer_id
    type: integer
    required: true
    rules:
      not_null: true
  - name: product_type
    type: string
    required: true
    rules:
      enum: [term, revolver]
  - name: status
    type: string
    required: true
    rules:
      enum: [active, delinquent, closed]
  - name: currency
    type: string
    required: true
    rules:
      regex: '^[A-Z]{3}$'
  - name: principal_balance
    type: float
    required: true
    rules:
      min: 0
      max: 20000000.0
      not_null: true
  - name: interest_rate
    type: float
    required: true
    rules:
      min: 0
      max: 0.25
  - name: opened_at
    type: string
    required: true
    rules:
      regex: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$'
