# ============================================================================
# PRODUCER CONTRACT: Deposit Transactions
# ============================================================================
# Scenario: Commercial & Institutional Banking Data Product (NatWest-style)
# Owner: Data Product Team (Producer)
# Strictness: STRICT - Authoritative transaction history
#
# Business Purpose:
#   - Complete transaction history for all deposit accounts
#   - Enforces strict transaction type classification and amount limits
#   - All fields required with no nulls for audit trail integrity
#   - Used by Deposits Operations for reconciliation and reporting
#
# Key Rules:
#   - txn_id: unique transaction identifier
#   - account_id: foreign key to deposit_accounts (must exist)
#   - txn_type: credit, debit, or fee only (strict classification)
#   - txn_amount: 0 to 5M range (large commercial transactions)
#   - txn_ts: transaction timestamp in YYYY-MM-DD HH:MM:SS format
#   - channel: branch, online, or api (source tracking)
# ============================================================================

contract:
  name: producer_deposit_transactions
  version: 2.0.0
dataset:
  name: deposit_transactions
fields:
  - name: txn_id
    type: integer
    required: true
    rules:
      not_null: true
      unique: true
  - name: account_id
    type: integer
    required: true
    rules:
      not_null: true
  - name: txn_type
    type: string
    required: true
    rules:
      enum: [credit, debit, fee]
  - name: txn_amount
    type: float
    required: true
    rules:
      min: 0
      max: 5000000.0
      not_null: true
  - name: txn_ts
    type: string
    required: true
    rules:
      regex: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$'
  - name: channel
    type: string
    required: true
    rules:
      enum: [branch, online, api]
