# ============================================================================
# PRODUCER CONTRACT: Loan Payments
# ============================================================================
# Scenario: Commercial & Institutional Banking Data Product (NatWest-style)
# Owner: Data Product Team (Producer)
# Strictness: STRICT - Authoritative payment history
#
# Business Purpose:
#   - Complete payment history for all commercial and institutional loans
#   - Enforces strict payment amount limits and status tracking
#   - All fields required with no nulls for financial reporting integrity
#   - Used by Lending Operations for cash flow and delinquency tracking
#
# Key Rules:
#   - payment_id: unique payment identifier
#   - loan_id: foreign key to lending_loans (must exist)
#   - payment_amount: 0 to 5M range (large commercial payments)
#   - payment_ts: payment timestamp in YYYY-MM-DD HH:MM:SS format
#   - payment_status: posted, pending, or failed (processing status)
# ============================================================================

contract:
  name: producer_loan_payments
  version: 2.0.0
dataset:
  name: loan_payments
fields:
  - name: payment_id
    type: integer
    required: true
    rules:
      not_null: true
      unique: true
  - name: loan_id
    type: integer
    required: true
    rules:
      not_null: true
  - name: payment_amount
    type: float
    required: true
    rules:
      min: 0
      max: 5000000.0
      not_null: true
  - name: payment_ts
    type: string
    required: true
    rules:
      regex: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$'
  - name: payment_status
    type: string
    required: true
    rules:
      enum: [posted, pending, failed]
