contract:
  name: producer_loan_payments
  version: 2.0.0
dataset:
  name: loan_payments
fields:
  - name: payment_id
    type: integer
    required: true
    rules:
      not_null: true
      unique: true
  - name: loan_id
    type: integer
    required: true
    rules:
      not_null: true
  - name: payment_amount
    type: float
    required: true
    rules:
      min: 0
      max: 5000000.0
      not_null: true
  - name: payment_ts
    type: string
    required: true
    rules:
      regex: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$'
  - name: payment_status
    type: string
    required: true
    rules:
      enum: [posted, pending, failed]
